# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec1b9c0c4deb5469a0f01320c44ffdb42ede5670f89226f81508a5c67d763921c8647f16d93fb4b2a462138a20645a8b60ee3cb7c5645a97f3cd92f74b2abd72

test:
  secret_key_base: 75881679c63eebe654eeb225a8227a6463bb7dc9d0edcb9f8dc5f3668a8d81d471b2d2c83e12876c4a43787e322263f04c4395a4bd2c653056f179a4683013ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
